// TEMPORARY DATA LAYER (V1)
import { Player } from '@/types'

export const mockPlayers: Player[] = [
  {
    id: 'player-1',
    firstName: 'Ethan',
    lastName: 'Cross',
    dateOfBirth: '2010-04-12',
    ageGroup: 'U14',
    position: 'MID',
    jerseyNumber: 8,
    membershipId: 'mem-1',
    sessionsRemaining: 6,
    totalSessionsAttended: 34,
    parentIds: ['parent-1'],
    groupIds: ['group-1'],
    joinedAt: '2023-09-01T00:00:00Z',
    status: 'active',
    performance: { speed: 82, agility: 78, endurance: 85, strength: 70, technicalScore: 88, lastAssessed: '2026-02-15T00:00:00Z' },
  },
  {
    id: 'player-2',
    firstName: 'Sofia',
    lastName: 'Martinez',
    dateOfBirth: '2010-08-23',
    ageGroup: 'U14',
    position: 'FWD',
    jerseyNumber: 9,
    membershipId: 'mem-2',
    sessionsRemaining: 8,
    totalSessionsAttended: 28,
    parentIds: ['parent-2'],
    groupIds: ['group-1'],
    joinedAt: '2023-11-14T00:00:00Z',
    status: 'active',
    performance: { speed: 90, agility: 86, endurance: 80, strength: 72, technicalScore: 91, lastAssessed: '2026-02-15T00:00:00Z' },
  },
  {
    id: 'player-3',
    firstName: 'Noah',
    lastName: 'Patel',
    dateOfBirth: '2010-01-30',
    ageGroup: 'U14',
    position: 'DEF',
    jerseyNumber: 5,
    membershipId: 'mem-3',
    sessionsRemaining: 0,
    totalSessionsAttended: 41,
    parentIds: ['parent-3'],
    groupIds: ['group-1'],
    joinedAt: '2022-08-20T00:00:00Z',
    status: 'active',
    performance: { speed: 74, agility: 80, endurance: 88, strength: 82, technicalScore: 76, lastAssessed: '2026-01-20T00:00:00Z' },
  },
  {
    id: 'player-4',
    firstName: 'Aiden',
    lastName: 'Thompson',
    dateOfBirth: '2011-03-05',
    ageGroup: 'U14',
    position: 'MID',
    jerseyNumber: 10,
    membershipId: 'mem-4',
    sessionsRemaining: 6,
    totalSessionsAttended: 19,
    parentIds: ['parent-4'],
    groupIds: ['group-1'],
    joinedAt: '2024-01-10T00:00:00Z',
    status: 'active',
    performance: { speed: 76, agility: 82, endurance: 77, strength: 65, technicalScore: 84, lastAssessed: '2026-02-01T00:00:00Z' },
  },
  {
    id: 'player-5',
    firstName: 'Maya',
    lastName: 'Johnson',
    dateOfBirth: '2010-11-18',
    ageGroup: 'U14',
    position: 'GK',
    jerseyNumber: 1,
    membershipId: null,
    sessionsRemaining: 0,
    totalSessionsAttended: 8,
    parentIds: ['parent-5'],
    groupIds: ['group-1'],
    joinedAt: '2025-09-05T00:00:00Z',
    status: 'active',
  },
  {
    id: 'player-6',
    firstName: 'Liam',
    lastName: 'Chen',
    dateOfBirth: '2012-06-14',
    ageGroup: 'U12',
    position: 'MID',
    jerseyNumber: 6,
    membershipId: 'mem-5',
    sessionsRemaining: 8,
    totalSessionsAttended: 22,
    parentIds: ['parent-6'],
    groupIds: ['group-2'],
    joinedAt: '2024-03-01T00:00:00Z',
    status: 'active',
    performance: { speed: 70, agility: 75, endurance: 72, strength: 60, technicalScore: 79, lastAssessed: '2026-01-28T00:00:00Z' },
  },
  {
    id: 'player-7',
    firstName: 'Zoe',
    lastName: 'Williams',
    dateOfBirth: '2012-09-02',
    ageGroup: 'U12',
    position: 'FWD',
    jerseyNumber: 11,
    membershipId: 'mem-6',
    sessionsRemaining: 7,
    totalSessionsAttended: 15,
    parentIds: ['parent-6'],
    groupIds: ['group-2'],
    joinedAt: '2024-03-01T00:00:00Z',
    status: 'active',
    performance: { speed: 85, agility: 88, endurance: 74, strength: 58, technicalScore: 80, lastAssessed: '2026-01-28T00:00:00Z' },
  },
  {
    id: 'player-8',
    firstName: 'Carlos',
    lastName: 'Reyes',
    dateOfBirth: '2013-02-25',
    ageGroup: 'U12',
    position: 'DEF',
    jerseyNumber: 4,
    membershipId: 'mem-7',
    sessionsRemaining: 10,
    totalSessionsAttended: 30,
    parentIds: ['parent-7'],
    groupIds: ['group-2'],
    joinedAt: '2023-06-15T00:00:00Z',
    status: 'active',
  },
  {
    id: 'player-9',
    firstName: 'Isabelle',
    lastName: 'Park',
    dateOfBirth: '2012-12-10',
    ageGroup: 'U12',
    position: 'MID',
    jerseyNumber: 7,
    membershipId: 'mem-8',
    sessionsRemaining: 1,
    totalSessionsAttended: 12,
    parentIds: ['parent-8'],
    groupIds: ['group-2'],
    joinedAt: '2024-08-20T00:00:00Z',
    status: 'active',
  },
  {
    id: 'player-10',
    firstName: 'James',
    lastName: 'Okafor',
    dateOfBirth: '2009-07-08',
    ageGroup: 'U16',
    position: 'GK',
    jerseyNumber: 1,
    membershipId: 'mem-9',
    sessionsRemaining: 15,
    totalSessionsAttended: 55,
    parentIds: ['parent-9'],
    groupIds: ['group-3'],
    joinedAt: '2021-09-01T00:00:00Z',
    status: 'active',
    performance: { speed: 72, agility: 85, endurance: 80, strength: 78, technicalScore: 92, lastAssessed: '2026-02-20T00:00:00Z' },
  },
  {
    id: 'player-11',
    firstName: 'Alex',
    lastName: 'Nguyen',
    dateOfBirth: '2009-04-17',
    ageGroup: 'U16',
    position: 'GK',
    jerseyNumber: 13,
    membershipId: 'mem-10',
    sessionsRemaining: 9,
    totalSessionsAttended: 38,
    parentIds: ['parent-10'],
    groupIds: ['group-3'],
    joinedAt: '2022-02-14T00:00:00Z',
    status: 'active',
    performance: { speed: 68, agility: 82, endurance: 78, strength: 74, technicalScore: 87, lastAssessed: '2026-02-20T00:00:00Z' },
  },
  {
    id: 'player-12',
    firstName: 'Taylor',
    lastName: 'Brooks',
    dateOfBirth: '2008-10-30',
    ageGroup: 'U16',
    position: 'GK',
    jerseyNumber: 30,
    membershipId: 'mem-11',
    sessionsRemaining: 0,
    totalSessionsAttended: 47,
    parentIds: ['parent-11'],
    groupIds: ['group-3'],
    joinedAt: '2021-09-01T00:00:00Z',
    status: 'active',
    performance: { speed: 66, agility: 80, endurance: 82, strength: 80, technicalScore: 89, lastAssessed: '2026-01-10T00:00:00Z' },
  },
  {
    id: 'player-13',
    firstName: 'Kai',
    lastName: 'Hernandez',
    dateOfBirth: '2007-03-22',
    ageGroup: 'U18',
    position: 'FWD',
    jerseyNumber: 9,
    membershipId: 'mem-12',
    sessionsRemaining: 20,
    totalSessionsAttended: 72,
    parentIds: ['parent-12'],
    groupIds: ['group-4'],
    joinedAt: '2020-09-01T00:00:00Z',
    status: 'active',
    performance: { speed: 94, agility: 90, endurance: 92, strength: 85, technicalScore: 95, lastAssessed: '2026-02-22T00:00:00Z' },
  },
  {
    id: 'player-14',
    firstName: 'Jordan',
    lastName: 'Lee',
    dateOfBirth: '2007-09-14',
    ageGroup: 'U18',
    position: 'MID',
    jerseyNumber: 8,
    membershipId: 'mem-13',
    sessionsRemaining: 6,
    totalSessionsAttended: 61,
    parentIds: ['parent-13'],
    groupIds: ['group-4'],
    joinedAt: '2021-01-15T00:00:00Z',
    status: 'active',
    performance: { speed: 88, agility: 91, endurance: 89, strength: 80, technicalScore: 93, lastAssessed: '2026-02-22T00:00:00Z' },
  },
  {
    id: 'player-15',
    firstName: 'Riley',
    lastName: 'Santos',
    dateOfBirth: '2007-01-03',
    ageGroup: 'U18',
    position: 'DEF',
    jerseyNumber: 5,
    membershipId: 'mem-14',
    sessionsRemaining: 2,
    totalSessionsAttended: 68,
    parentIds: ['parent-14'],
    groupIds: ['group-4'],
    joinedAt: '2020-09-01T00:00:00Z',
    status: 'active',
    performance: { speed: 82, agility: 84, endurance: 90, strength: 88, technicalScore: 86, lastAssessed: '2026-02-22T00:00:00Z' },
  },
  {
    id: 'player-16',
    firstName: 'Oliver',
    lastName: 'Davis',
    dateOfBirth: '2014-05-11',
    ageGroup: 'U10',
    position: 'FWD',
    jerseyNumber: 10,
    membershipId: 'mem-15',
    sessionsRemaining: 7,
    totalSessionsAttended: 10,
    parentIds: ['parent-15'],
    groupIds: ['group-5'],
    joinedAt: '2025-09-08T00:00:00Z',
    status: 'active',
  },
  {
    id: 'player-17',
    firstName: 'Ella',
    lastName: 'Moore',
    dateOfBirth: '2015-08-29',
    ageGroup: 'U10',
    position: 'MID',
    jerseyNumber: 7,
    membershipId: 'mem-16',
    sessionsRemaining: 5,
    totalSessionsAttended: 8,
    parentIds: ['parent-15'],
    groupIds: ['group-5'],
    joinedAt: '2025-09-08T00:00:00Z',
    status: 'active',
  },
  {
    id: 'player-18',
    firstName: 'Lucas',
    lastName: 'Wilson',
    dateOfBirth: '2014-11-04',
    ageGroup: 'U10',
    position: 'DEF',
    jerseyNumber: 3,
    membershipId: 'mem-17',
    sessionsRemaining: 11,
    totalSessionsAttended: 14,
    parentIds: ['parent-16'],
    groupIds: ['group-5'],
    joinedAt: '2025-01-12T00:00:00Z',
    status: 'active',
  },
]

export function getPlayerById(id: string): Player | undefined {
  return mockPlayers.find(p => p.id === id)
}

export function getPlayersByGroup(groupId: string): Player[] {
  return mockPlayers.filter(p => p.groupIds.includes(groupId))
}

export function getPlayersByAgeGroup(ageGroup: string): Player[] {
  return mockPlayers.filter(p => p.ageGroup === ageGroup)
}

export function searchPlayers(query: string): Player[] {
  const q = query.toLowerCase().trim()
  if (!q) return mockPlayers
  return mockPlayers.filter(p =>
    p.firstName.toLowerCase().includes(q) ||
    p.lastName.toLowerCase().includes(q) ||
    `${p.firstName} ${p.lastName}`.toLowerCase().includes(q) ||
    p.id.toLowerCase().includes(q) ||
    (p.jerseyNumber?.toString() === q)
  )
}
