import type { NavItem } from '@/lib/nav/types'

/** Central navigation for Formula Admin OS - facility operating system, not generic gym software */
export const adminNav: NavItem[] = [
  {
  label: 'Dashboard',
  href: '/admin/dashboard',
  icon: 'LayoutDashboard',
  description: 'Command grid · cross-console snapshot',
  gridStatus: 'neutral',
  },
  {
  label: 'Executive',
  href: '/admin/overview',
  icon: 'Activity',
  description: 'Daily ops snapshot · blocks · utilization · revenue · alerts',
  gridStatus: 'active',
  },
  {
  label: 'Schedule',
  href: '/admin/schedule',
  icon: 'Calendar',
  description: '55m engine · buffers · 12-week cycles · overrides + audit',
  gridStatus: 'neutral',
  },
  {
  label: 'Ops map',
  href: '/admin/facility-map',
  icon: 'Layers',
  description: 'Live asset control surface · inventory protection',
  gridStatus: 'neutral',
  },
  {
  label: 'Check-In',
  href: '/admin/check-in',
  icon: 'UserCheck',
  badge: 'LIVE',
  badgeVariant: 'accent',
  description: 'Attendance · wristband · roster verification',
  gridStatus: 'active',
  },
  {
  label: 'Memberships',
  href: '/admin/memberships',
  icon: 'CreditCard',
  description: 'Age bands · tiers · waitlist · scarcity',
  gridStatus: 'neutral',
  },
  {
  label: 'FPI',
  href: '/admin/fpi',
  icon: 'Gauge',
  description: 'Internal model · pillars · assessments · QC',
  gridStatus: 'neutral',
  },
  {
  label: 'Friday circuit',
  href: '/admin/friday-circuit',
  icon: 'Trophy',
  description: 'Pre-reg · rosters · observation · no pickup culture',
  gridStatus: 'neutral',
  },
  {
  label: 'Adult',
  href: '/admin/adult-programming',
  icon: 'CalendarClock',
  description: 'Pickup · leagues · caps vs youth identity',
  gridStatus: 'neutral',
  },
  {
  label: 'Clinics',
  href: '/admin/clinics',
  icon: 'ClipboardList',
  description: 'Scarce labs · FPI-driven access · outcomes',
  gridStatus: 'neutral',
  },
  {
  label: 'Rentals',
  href: '/admin/rentals',
  icon: 'Building2',
  description: 'Structured packages · prime/off-peak · alignment',
  gridStatus: 'neutral',
  },
  {
  label: 'Events',
  href: '/admin/events-layer',
  icon: 'Flame',
  description: 'Camps · tournaments · parties · Footbot',
  gridStatus: 'neutral',
  },
  {
  label: 'Revenue',
  href: '/admin/revenue-strategy',
  icon: 'BarChart2',
  description: 'Mix discipline · thresholds · phase framing',
  gridStatus: 'warning',
  },
  {
  label: 'Players',
  href: '/admin/players',
  icon: 'Users',
  description: 'Registry · medical · roster',
  gridStatus: 'neutral',
  },
  {
  label: 'Payments',
  href: '/admin/payments',
  icon: 'DollarSign',
  description: 'Ledger · categories',
  gridStatus: 'neutral',
  },
  {
  label: 'Performance',
  href: '/admin/performance',
  icon: 'TrendingUp',
  description: 'Athlete views · machine feeds',
  gridStatus: 'neutral',
  },
  {
  label: 'Scale',
  href: '/admin/scalability',
  icon: 'Network',
  description: 'Multi-site · FPI central · SOP · licensing',
  gridStatus: 'neutral',
  },
  {
  label: 'Settings',
  href: '/admin/settings',
  icon: 'Settings',
  description: 'RBAC · integrations · facility profile',
  gridStatus: 'neutral',
  },
]
